document.writeln("<div class=\'share floatfrm\'>");
document.writeln("<div class=\'con\'>");
document.writeln("<div id=\'bdshare\' class=\'bdshare_t bds_tools_32 get-codes-bdshare\'>");
document.writeln("<a class=\'bds_qzone\'></a>");
document.writeln("<a class=\'bds_tsina\'></a>");
document.writeln("<a class=\'bds_tqq\'></a>");
document.writeln("<a class=\'bds_renren\'></a>");
document.writeln("<a class=\'bds_t163\'></a>");
document.writeln("<span class=\'bds_more\'></span>");
document.writeln("<a class=\'shareCount\'></a>");
document.writeln("</div>");
document.writeln("<script type=\'text/javascript\' id=\'bdshare_js\' data=\'type=tools&amp;uid=6812889\' ></script>");
document.writeln("<script type=\'text/javascript\' id=\'bdshell_js\'></script>");
document.writeln("<script type=\'text/javascript\'>");
document.writeln("document.getElementById(\'bdshell_js\').src = \'//bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=\' + Math.ceil(new Date()/3600000)");
document.writeln("</script></div>");
document.writeln("</div>");
document.writeln("<div class=\'info\'>");
document.writeln("<p align=\'left\'>");
document.writeln("<font color=\'#FF0000\'>重要说明</font>：中文期刊网持有《出版物经营许可证》和《增值电信业务经营许可证》，依法从事国内所有合法期刊订阅及第二类增值电信业务中的信息服务业务(互联网信息服务)，本站主要从事订阅业务，不是任何杂志官网，直投稿件的朋友建议联系杂志社编辑部！");
document.writeln("</div>");