document.writeln("    <div class=\"pub boxnav\">");
document.writeln("    	<div class=\"floatfrm\">");
document.writeln("            <dl>");
document.writeln("            	<dt><a href=\"\/a\/lunwenziliao\/jingjilunwen\/\" title=\"经济论文\">经济<\/a><\/dt>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/jingjilunwen\/guquantouzilunwen\/\" title=\"股权投资论文\">股权<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/jingjilunwen\/dangdaihaiyangjingjilu\/\" title=\"当代海洋经济论文\">海洋<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/jingjilunwen\/ditanjingjituozhanlunw\/\" title=\"低碳经济拓展论文\">低碳<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/jingjilunwen\/xingyejingji\/\" title=\"行业经济\">行业<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/jiaoyulunwen\/zhiyejiaoyu\/\" title=\"职业教育\">乡村<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/jingjilunwen\/huobijinrong\/\" title=\"货币金融\">货币<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/jingjilunwen\/hongguanjingjixuelunwe\/\" title=\"宏观经济学论文\">宏观经济<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/jingjilunwen\/zhengzhijingjixuelunwe\/\" title=\"政治经济学论文\">政治经济<\/a><\/dd>");
document.writeln("            <\/dl>");
document.writeln("            <dl>");
document.writeln("            	<dt><a href=\"\/a\/lunwenziliao\/jiaoyulunwen\/\" title=\"教育论文\">教育<\/a><\/dt>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/jiaoyulunwen\/sanshengjiaoyujiaoxuel\/\" title=\"三生教育教学论文\">教学<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/jiaoyulunwen\/kechenggaigelunwen\/\" title=\"课程改革论文\">课改<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/jiaoyulunwen\/daxuejiaoyulunwen\/\" title=\"大学教育论文\">大学<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/jiaoyulunwen\/chengrenzhiyejiaoyulun\/\" title=\"成人职业教育论文\">成教<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/guanlilunwen\/tushuguanzhuanyeguanli\/\" title=\"图书馆专业管理论文\">语文<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/jiaoyulunwen\/yingyulunwen\/\" title=\"英语论文\">英语<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/jiaoyulunwen\/banzhurendeyujiaoyulun\/\" title=\"班主任德育教育论文\">班主任<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/jiaoyulunwen\/jiaoyuyanjiu\/\" title=\"教育研究\">教育研究<\/a><\/dd>");
document.writeln("            <\/dl>");
document.writeln("            <dl>");
document.writeln("            	<dt><a href=\"\/a\/lunwenziliao\/guanlilunwen\/\" title=\"管理论文\">管理<\/a><\/dt>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/guanlilunwen\/qiyeguanli\/\" title=\"企业管理\">企业<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/guanlilunwen\/renliziyuan\/\" title=\"人力资源\">人力<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/guanlilunwen\/gonggongguanli\/\" title=\"公共管理\">公共<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/guanlilunwen\/lvyouguanli\/\" title=\"旅游管理\">旅游<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/guanlilunwen\/huijishenji\/\" title=\"会计审计\">会计<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/guanlilunwen\/caiwuguanli\/\" title=\"财务管理\">财务<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/guanlilunwen\/shichangyingxiao\/\" title=\"市场营销\">营销<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/guanlilunwen\/xiangmuguanlilunwen\/\" title=\"项目管理论文\">项目<\/a><\/dd>");
document.writeln("            <\/dl>");
document.writeln("            <dl>");
document.writeln("            	<dt><a href=\"\/yixuelunwen\/\" title=\"医学论文\">医学<\/a><\/dt>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/zirankexue\/kouqiangkezhiliaolunwen\/\" title=\"口腔科治疗论文\">口腔<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/zirankexue\/yankelunwen\/\" title=\"眼科临床论文\">眼科<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/zirankexue\/hulifangfalunwen\/\" title=\"护理方法论文\">护理<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/zirankexue\/jizhenqiangjiulunwen\/\" title=\"急诊抢救论文\">急诊<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/zirankexue\/mazuixuelunwen\/\" title=\"麻醉学论文\">麻醉<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/zirankexue\/weishenggaigelunwen\/\" title=\"卫生改革论文\">医改<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/zirankexue\/fuchankelunwen\/\" title=\"妇产科论文\">妇产科<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/zirankexue\/pifukelunwen\/\" title=\"皮肤科论文\">皮肤科<\/a><\/dd>");
document.writeln("            <\/dl>");
document.writeln("            <dl>");
document.writeln("            	<dt><a href=\"\/a\/lunwenziliao\/shengtaixuelunwen\/\" title=\"生态学论文\">生态<\/a><\/dt>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/shengtaixuelunwen\/chengshishengtail\/\" title=\"城市生态论文\">城市<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/shengtaixuelunwen\/shengtailvyoulunw\/\" title=\"生态旅游论文\">旅游<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/shengtaixuelunwen\/nongyeshengtaijia\/\" title=\"农业生态建设论文\">农业<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/shengtaixuelunwen\/shengtaiwenminglu\/\" title=\"生态文明论文\">生态文明<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/shengtaixuelunwen\/shengtaixiaofeilu\/\" title=\"生态消费论文\">生态消费<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/shengtaixuelunwen\/shengtaijianshelu\/\" title=\"生态建设论文\">生态建设<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/shengtaixuelunwen\/shengtaibaohulunw\/\" title=\"生态保护论文\">生态保护<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/shengtaixuelunwen\/shengtaixiufulunw\/\" title=\"生态修复论文\">生态修复<\/a><\/dd>");
document.writeln("            <\/dl>");
document.writeln("            <dl>");
document.writeln("            	<dt><a href=\"\/a\/lunwenziliao\/zhengquanlunwen\/\" title=\"证券论文\">证券<\/a><\/dt>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/zhengquanlunwen\/zhengquanshichanglu\/\" title=\"证券市场论文\">市场<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/zhengquanlunwen\/zhengquanjiaoyilunw\/\" title=\"证券交易论文\">交易<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/zhengquanlunwen\/zhengquantouzilunwe\/\" title=\"证券投资论文\">投资<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/zhengquanlunwen\/zhengquanzhidulunwe\/\" title=\"证券制度论文\">制度<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/jingjilunwen\/xindaiguanlilunwen\/\" title=\"信贷管理论文\">信贷<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/jingjilunwen\/qiyeshuishoulunwen\/\" title=\"企业税收论文\">税收<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/jingjilunwen\/caiwubaobiaolunwen\/\" title=\"财务报表论文\">报表<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/jingjilunwen\/qihuoshichanglunwen\/\" title=\"期货市场论文\">期货<\/a><\/dd>");
document.writeln("            <\/dl>");
document.writeln("            <dl>");
document.writeln("            	<dt><a href=\"\/a\/lunwenziliao\/wenxuelunwen\/\" title=\"文学论文\">文学<\/a><\/dt>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/wenxuelunwen\/xiandaiwenxuelunwen\/\" title=\"现代文学论文\">现代<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/wenxuelunwen\/dangdaiwenxuelunwen\/\" title=\"当代文学论文\">当代<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/wenxuelunwen\/gudaiwenxuelunwen\/\" title=\"古代文学论文\">古代<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/wenxuelunwen\/waiguowenxuelunwen\/\" title=\"外国文学论文\">外国<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/wenxuelunwen\/xiandaishige\/\" title=\"现代诗歌论文\">诗歌<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/wenxuelunwen\/xiandaixiaoshuolunwen\/\" title=\"现代小说论文\">小说<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/wenxuelunwen\/yingyuwenxuelunwen\/\" title=\"英语文学论文\">英语<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/wenxuelunwen\/hanyuyanwenxuelunwen\/\" title=\"汉语言文学论文\">汉语言<\/a><\/dd>");
document.writeln("            <\/dl>");
document.writeln("            <dl>");
document.writeln("            	<dt><a href=\"\/a\/lunwenziliao\/wenhualunwen\/\" title=\"文化论文\">文化<\/a><\/dt>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/wenhualunwen\/chawenhualunwen\/\" title=\"茶文化论文\">茶<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/wenhualunwen\/jiuwenhualunwen\/\" title=\"酒文化论文\">酒<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/wenhualunwen\/zongjiaowenhualunwen\/\" title=\"宗教文化论文\">宗教<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/wenhualunwen\/wenhuafazhanlunwen\/\" title=\"文化发展论文\">文化发展<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/wenhualunwen\/wenhuachanyelunwen\/\" title=\"文化产业论文\">文化产业<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/wenhualunwen\/chuantongwenxuefazhanl\/\" title=\"传统文学发展论文\">传统文学<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/wenhualunwen\/jingshenwenhualunwen\/\" title=\"精神文化论文\">精神文化<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/wenhualunwen\/wenhualilunlunwen\/\" title=\"文化理论论文\">文化理论<\/a><\/dd>");
document.writeln("            <\/dl>");
document.writeln("            <dl>");
document.writeln("            	<dt><a href=\"\/a\/lunwenziliao\/wentilunwen\/\" title=\"文体论文\">文体<\/a><\/dt>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/wentilunwen\/meishu\/\" title=\"美术\">美术<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/wentilunwen\/yinle\/\" title=\"音乐\">音乐<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/wentilunwen\/tiyu\/\" title=\"体育\">体育<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/wentilunwen\/yingshiguanggaolunwen\/\" title=\"影视广告论文\">影视<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/wentilunwen\/dianyingshichanglunwen\/\" title=\"电影市场论文\">戏曲<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/wentilunwen\/jiajushejilunwen\/\" title=\"家具设计论文\">家具<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/wentilunwen\/jingguanshejilunwen\/\" title=\"景观设计论文\">景观<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/wentilunwen\/zaoxingyishulunwen\/\" title=\"造型艺术论文\">造型<\/a><\/dd>");
document.writeln("            <\/dl>");
document.writeln("            <dl>");
document.writeln("            	<dt><a href=\"\/a\/lunwenziliao\/shehuikexue\/\" title=\"社会科学\">社会科学<\/a><\/dt>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/shehuikexue\/dangjianxingzheng\/\" title=\"党建行政\">党建<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/shehuikexue\/baoxianbaozhang\/\" title=\"保险保障\">保险<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/shehuikexue\/xinwenchuanbo\/\" title=\"新闻传播\">新闻<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/shehuikexue\/dianzijishulunwen\/\" title=\"电子技术论文\">电子<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/shehuikexue\/jixiezhizaolunwen\/\" title=\"机械制造论文\">机械<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/shehuikexue\/wangluogongchenglunwen\/\" title=\"网络工程论文\">网络工程<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/shehuikexue\/weijichuanbolunwen\/\" title=\"危机传播论文\">危机传播<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/shehuikexue\/zhengzhiwaijiao\/\" title=\"政治外交\">政治外交<\/a><\/dd>");
document.writeln("            <\/dl>");
document.writeln("            <dl>");
document.writeln("            	<dt><a href=\"\/a\/lunwenziliao\/zirankexue\/\" title=\"自然科学\">自然科学<\/a><\/dt>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/zirankexue\/nongyejiaoyulunwen\/\" title=\"农业教育论文\">农业<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/zirankexue\/shuilisheshilunwen\/\" title=\"水利设施论文\">水利<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/zirankexue\/yixuejiaoyukejilunwen\/\" title=\"医学教育科技论文\">医学<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/zirankexue\/weishenggaigelunwen\/\" title=\"卫生改革论文\">卫生<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/zirankexue\/huanjinggongchengxuelunw\/\" title=\"环境工程学论文\">环境<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/zirankexue\/dizhixuelunwen\/\" title=\"地质学论文\">地质<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/zirankexue\/xumuyelunwen\/\" title=\"畜牧业论文\">畜牧业<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/zirankexue\/gongxue\/\" title=\"计算机\">计算机<\/a><\/dd>");
document.writeln("            <\/dl>");
document.writeln("            <dl>");
document.writeln("            	<dt><a href=\"\/a\/lunwenziliao\/waiyulunwen\/\" title=\"文史哲学\">文史哲学<\/a><\/dt>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/waiyulunwen\/yuyanwenhua\/\" title=\"语言文化\">语言<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/waiyulunwen\/yingyujiaoxue\/\" title=\"英语教学\">英语<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/waiyulunwen\/yingmeiwenxue\/\" title=\"英美文学\">英美<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/jingjilunwen\/hongguanjingji\/\" title=\"宏观经济\">考古<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/waiyulunwen\/lunlixuelunwen\/\" title=\"伦理学论文\">伦理<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/waiyulunwen\/waiyufanyi\/\" title=\"外语翻译\">翻译<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/waiyulunwen\/zhexuesixianglunwen\/\" title=\"哲学思想论文\">哲学<\/a><\/dd>");
document.writeln("            	<dd><a href=\"\/a\/lunwenziliao\/waiyulunwen\/xingshiluojilunwen\/\" title=\"形式逻辑论文\">逻辑<\/a><\/dd>");
document.writeln("            <\/dl>");
document.writeln("        <\/div>");
document.writeln("    <\/div>");
document.writeln("    <div class=\"h10nb\"><\/div>")